### ISSUE TITLE
Précisions .gitignore

### ISSUE THREAD

**Issue by blupdew** [alsacreations/bretzel#10]
Pour `src/vendor/` ne vaudrait-il pas mieux écrire `/src/vendor/` ? Pour n'isoler que ce dossier depuis la racine et pas les autres potentiels ?

Pareil pour `/dist/` plutôt que `dist/` ?

Sur le même principe ne risque-t-on pas d'avoir des problèmes avec `Icon` qui pourrait concerner des fichiers de contenu uploadés comprenant ces lettres ?

Et toujours dans la même lignée, les dossiers `Network Trash Folder`, `Temporary Items`, sont-ils à préfixer avec `/` ?

**Comment by raphaelgoetter** [comment]
ça me semble cohérent, je n'y vois pas d'objection.

**Comment by hiwelo** [comment]
Pour les parties du *.gitignore* concernant Mac OS X, j'aurais tendance à ne pas mettre de `/` au début, car ces fichiers et dossiers cachés peuvent être créés dans n'importe quel dossier de l'arborescence.
Côté *Icon*, ça n'a jamais posé de question dans les projets dans lesquels j'ai mis les pieds. :smile: 

Enfin, pour `/src/vendor/` et `/dist/` ça me paraît aussi plus cohérent :smile:

**Comment by raphaelgoetter** [comment]
@blupdew tu t'en charges ? c'est déjà fait ? tu veux que je m'en charge ?

**Comment by raphaelgoetter** [comment]
up

**Comment by raphaelgoetter** [comment]
up

**Comment by raphaelgoetter** [comment]
up

**Comment by raphaelgoetter** [comment]
abandonné
