### ISSUE TITLE
problème de choix dans la date

### ISSUE THREAD

**Issue by raphaelgoetter** [alsacreations/bretzel#14]
La tâche "gulp build-zip" / "gulp prod-zip" construit un fichier archive zip dont le nom comporte la date actuelle.

Or la date n'est pas correcte.

J'écris : `var date = d.getFullYear() + '-' + d.getMonth() + '-' + d.getDate() + '-' + d.getHours() + 'h' + d.getMinutes();` et j'obtiens ... `*** - 2016-0-5-17h40.zip` (on est le 5 janvier 2016).

Qui peut me donner un format de date correct ? Merci 

Ping @blupdew @id2 @alsacreations/les-coupains

**Comment by hiwelo** [comment]
Hello
C'est un soucis assez connu, getMonth retourne une valeur entre 0 et 11.
Il suffit donc simplement de faire +1 sur le mois retourné.

Pour info, tu peux regarder du côté de MDN : https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Objets_globaux/Date/getMonth

Je viens de créer une pull request avec une modification qui devrait corriger ça. :smile_cat:
