### ISSUE TITLE
vers une version publique ?

### ISSUE THREAD

**Issue by raphaelgoetter** [alsacreations/bretzel#17]
Comme discuté lors d'une réunion récente, Bretzel pourrait parfaitement être ouvert au public (bon OK c'est déjà sur github public, mais je veux dire que pour le moment on ne communique pas dessus, on n'a pas de site dédié, de logo, etc.)

Dans cette optique, il y a de fortes chances pour que l'on doive "rendre le code actuel plus présentable", plus propre, plus classe (rassembler les variables, ajouter de la cohérence et de la maintenabilité, etc.)

Le ["alstart" de Damien](https://github.com/hiwelo/hwlo-portfolio/blob/develop/gulpfile.babel.js) est bien fichu et clair, mais pas forcément complètement adapté à Bretzel (en tout cas en l'état je ne comprends pas tout, ce qui ne me semble pas très pratique pour un outil "public" que tout le monde pourrait utiliser.)

Possibilité de partir de la base Bretzel et de rajouter un peu de "propreté" du projet de @hiwelo ?

**Comment by hiwelo** [comment]
Le mien est écrit en ES2015, avec nécessité de passer du coup par un système comme babel du coup je suis d'accord ce n'est pas forcément l'idéal pour un projet grand public.
Mais pour un code plus propre, l'idée d'avoir toutes les déclarations via des objets en début de fichier, y compris pour les options de certains plugins utilisés, je trouve ça assez cool.

Ça permet d'éviter de devoir mettre les mains dans le code systématiquement dès qu'on veut modifier quelque chose :) 
Perso, j'ai séparé les variables en deux objets : 
* un objet contenant les variables de projet (nom, préfixes ou suffixes de certains fichiers, etc.)
* un objet contenant les chemins de dossiers

J'y pense, mais pour en faire un projet public, il faudrait aussi remplacer le `Alsacreations` dans la task `zip` par une variable que chacun peut adapter selon ses projets.

**Comment by raphaelgoetter** [comment]
Ta séparation variables/chemins me plaît aussi.

Pour ce qui est du .zip, il y a déjà une partie variable qui est celle du nom du projet. Philippe a proposé de le préfixer systématiquement pas "Alsacreations" puisque c'est ce qu'on livre au client et ainsi il ne confond pas de prestataire. Je trouve ça cohérent. (et je trouve que ça compliquerait les choses de le passer via une variable supplémentaire)

**Comment by hiwelo** [comment]
Je trouve le préfixe intéressant, mais si tu souhaites rendre le projet grand public, ce n'est pas top d'avoir quelque part Alsacreations directement en brut dans le code ;)
Surtout pour quelque chose d'aussi sensible que des zip de livraison, tu ne penses pas ?

Si on passe par une variable, qui elle est définie initialement par Alsacreations, ça nous évite de devoir modifier cette variable à chaque projet mais ça permet de faciliter le changement pour ceux qui souhaitent récupérer ce gulpfile, non ? :smile_cat:

**Comment by raphaelgoetter** [comment]
C'est pas faux 😊

**Comment by raphaelgoetter** [comment]
bon ben ça c'est fait, merci :)
