### ISSUE TITLE
Séparer complètement les tâches unCSS et Critical

### ISSUE THREAD

**Issue by raphaelgoetter** [alsacreations/bretzel#21]
unCSS et Critical sont vraiment des tâches anecdotiques qui ne méritent pas forcément d'être intégrées au process de build et de prod, même commentées.

Je vais, sauf contre-avis : 
- les retirer du flux actuel pour en faire des tâches séparées
- les retirer du package.json (parce qu'on ne peut pas simplement commenter la ligne)

**Comment by raphaelgoetter** [comment]
Ah mais en fait les tâches unCSS et Critical plantent lorsqu'elles sont activées (mises à "true") : 

> TypeError: $.uncss is not a function

:(

**Comment by raphaelgoetter** [comment]
Je vais supprimer Critical, on ne s'en sert jamais.

**Comment by PhilippeVay** [comment]
OK on ne s'en est pas servi.

Ceci dit avec la disparition d'IE9 disparaissent les classes conditionnelles `.ie9` et cie, un truc qui ne fonctionnait pas par défaut avec UnCSS (et Critical je suppose) donc à réétudier un de ces jours amha

**Comment by hiwelo** [comment]
unCSS et Critical sont les deux tasks que j'ai pas pu tester.
Je n'ai pas de projet full-HTML sous la main pour cela :/

**Comment by PhilippeVay** [comment]
UnCSS utilise PhantomJS et il attend en paramètre des URLs. Autrement dit il n'y a pas que les pages statiques qui lui conviennent ; ça peut être du PHP, du WordPress ou autre.

Par contre il lui faut une liste _complète_ de ce qu'il peut rencontrer sans quoi il considérera que ce n'est pas utilisé dans le projet et il le supprimera. Pour nous ça revient à lui passer la liste des gabarits intégrés (*) et donc plus ou moins le full-HTML que tu évoques.
Et il faut lui préciser les MQ s'il en oublie ainsi que les sélecteurs pas "vus" au chargement de la page comme les modales, les menus burger, etc bref beaucoup de taf !

**Comment by hiwelo** [comment]
Effectivement, beaucoup de taf.
En dehors d'un projet en intégration continue, ça me paraît compliqué à mettre en place dans nos procédés de travail...
