### ISSUE TITLE
Erreur de BrowserSync

### ISSUE THREAD

**Issue by raphaelgoetter** [alsacreations/bretzel#23]
Je viens de tester mon premier  `gulp watch` depuis la dernière version et j'ai une erreur `ReferenceError: browserSync is not defined` à la ligne `browserSync.init(browserSyncConf);`

Je crois que c'est simplement parce que browserSync n'apparaît pas dans la partie "Chargement et initialisation des composants utilisés", non ?

EDIT : oui c'était ça, il suffit de penser à rajouter `browserSync = require('browser-sync').create(),` 
Je m'en occupe ce soir.

**Comment by hiwelo** [comment]
Ah tiens marrant, sur ma version locale j'ai testé browserSync et il démarrait o_O
Il faudrait que je regarde si la ligne n'a pas disparu quand je suis passé de mon test local à la branche pushée.
