### ISSUE TITLE
erreur des adresses .scss de /knacss dans /node_modules

### ISSUE THREAD

**Issue by ItIsInspiring** [alsacreations/bretzel#32]
Bonjour,
peut-on actualiser les adresses des partials dans node-modules/knacss/sass/ ?

Cordialement,

**Comment by ItIsInspiring** [comment]
Oups ! autant pour moi, je viens de ré-écrire mon fichier knacss.scss avec les bonnes adresses.
merci

**Comment by raphaelgoetter** [comment]
Le problème venait (aussi) du package.json de Bretzel qui pointait vers une ancienne version de KNACSS : ^4.4.4 au-lieu de ^5.0.0, cela devrait fonctionner mieux à présent, merci ;)

**Comment by ItIsInspiring** [comment]
ok super ! 
merci
