### ISSUE TITLE
Problème d'affichage sur IE11

### ISSUE THREAD

**Issue by ItIsInspiring** [alsacreations/bretzel#33]
Bonjour,
j'ai un projet web qui ne s'affiche pas correctement sur IE11 uniquement, genre comme si c'était IE8 T_T
Sinon : 
- le résultat est nikel sur Chrome et Mozilla. 
- Autoprefixer fonctionne correctement.

Je ne vois pas d'où peut venir le problème. Flexbox est plutôt bien géré après IE8 si je ne me trompe ?
Merci pour votre aide !

**Comment by PhilippeVay** [comment]
Bonjour,
Flexbox est supporté depuis IE10 et avec "la syntaxe de 2012" (la syntaxe intermédiaire n°2 sur 3) d'après [caniuse](http://caniuse.com/#search=flexbox)
IE11 utilise la dernière syntaxe, la même que Safari, Firefox et Chrome mais il y a pas mal de bugs, cf les [flexbugs](https://github.com/philipwalton/flexbugs).

- Est-ce que ton bug est décrit dans la liste ou dans les _known issues_ de caniuse ?
- Est-ce que tu vois les mêmes instructions CSS dans les DevTools d'un autre navigateur que F12 dans IE11 ?
- Est-ce que tu peux reproduire le problème dans un Codepen ?

**Comment by ItIsInspiring** [comment]
SOLUTION 
dans le <head>, il faut rajouter ceci  :
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />

dans le doctype de  src/index.html

**Comment by raphaelgoetter** [comment]
Bien vu, je viens de l'ajouter
