### ISSUE TITLE
Gulpfile.js - la tâche "fonts" ne copie pas les fichiers d'un sous-dossier

### ISSUE THREAD

**Issue by jnoesser** [alsacreations/bretzel#37]
Actuellement la tâche `gulp fonts` ne copie pas les fichiers d'un sous-répertoire présent dans `/fonts`, il se contente juste de copier le répertoire vide.

À la ligne 186, remplacer :
```
return gulp.src(paths.src + paths.fonts + '*')
```
par :
```
return gulp.src(paths.src + paths.fonts + '**/*')
```

**Comment by raphaelgoetter** [comment]
corrigé
