### ISSUE TITLE
Différences nommages variables

### ISSUE THREAD

**Issue by jbazin30** [alsacreations/bretzel#45]
Salut,

actuellement, dans le fichier [knacss.scss](https://github.com/alsacreations/bretzel/blob/master/src/assets/css/knacss.scss) sont importés : `_config/_variables.scss` et `./node_modules/knacss/sass/library/_base.scss`.

Or, dans `_base.scss` on utilise la variable `$background-base` (ligne 29), qui est déclarée sous le nom `$base-background : $color2;` dans `_config/_variables.scss` (ligne 28).

Le problème se pose pour ces variables :
```
$base-color: $color1;
$link-color: $color3;
$base-background : $color2;
$link-hover-color: $color4;
```

En ajoutant :
```
$color-base: $color1;
$color-link: $color3;
$background-base : $color2;
$color-link-hover: $color4;
```

dans `_variables.scss`, tout rentre dans l'ordre.

**Comment by raphaelgoetter** [comment]
Merci de l'avoir remarqué, je viens de faire la mise à jour.

**Comment by jbazin30** [comment]
Impec, merci.
